#!/bin/sh
#------------#
# Global Env #
#------------#

export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway

# export QT_AUTO_SCREEN_SCALE_FACTOR=1
# export QT_QPA_PLATFORM="wayland;xcb"
# export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
# export QT_QPA_PLATFORMTHEME=qt5ct

export GTK_THEME=Adwaita

dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

#-----------#
# Autostart #
#-----------#
# River will send the process group of the init executable SIGTERM on exit.

# Source config and maps (they are modules so that I can reload them
# without restarting all the programs above)
/home/user/.config/river/config &
/home/user/.config/river/maps &
wait

setbg -i &
foot --server &
fnott &
wlsunset -S 6:00 -s 21:00 -t 4000 -d 900 &
easyeffects --gapplication-service &
logseq &
yambar-reload &
kanshi &
qbittorrent &
nix-shell -p logseq --run 'setsid logseq > /dev/null 2> /dev/null &' &
