background: &background "101623ff"
foreground: &foreground "fff2f0ff"
selection: &selection "202d46ff"
red: &red "ff4766ff"
green: &green "a6c18bff"
yellow: &yellow "fb8950ff"

dmargin: &dmargin 16
margin: &margin 8
margin-side: &margin-side 4

bar:
  height: 26
  location: top
  background: *background
  foreground: *foreground
  font: monospace:pixelsize=19
  spacing: *margin
  margin: *margin
  trackpad-sensitivity: 40

  left:
    - script:
        path: ~/.local/bin/battery
        args:
          - "-y"
        poll-interval: 5000
        content:
          map:
            default:
              ramp:
                tag: capacity
                items:
                  - string: {text: "󰂎 {capacity}%"}
                  - string: {text: "󰁺 {capacity}%"}
                  - string: {text: "󰁼 {capacity}%"}
                  - string: {text: "󰁽 {capacity}%"}
                  - string: {text: "󰁾 {capacity}%"}
                  - string: {text: "󰁿 {capacity}%"}
                  - string: {text: "󰂀 {capacity}%"}
                  - string: {text: "󰂁 {capacity}%"}
                  - string: {text: "󰂂 {capacity}%"}
                  - string: {text: "󰁹 {capacity}%"}

            conditions:
              charging:
                ramp:
                  foreground: *yellow
                  tag: capacity
                  items:
                    - string: {text: "󰢜 {capacity}%"}
                    - string: {text: "󰂆 {capacity}%"}
                    - string: {text: "󰂇 {capacity}%"}
                    - string: {text: "󰂈 {capacity}%"}
                    - string: {text: "󰢝 {capacity}%"}
                    - string: {text: "󰂉 {capacity}%"}
                    - string: {text: "󰢞 {capacity}%"}
                    - string: {text: "󰂊 {capacity}%"}
                    - string: {text: "󰂋 {capacity}%"}
                    - string: {text: "󰂅 {capacity}%"}

    - backlight:
        name: intel_backlight
        content:
          string:
            text: "󰛨 {percent}%"
            on-click:
              wheel-up: "brightnessctl s 2%+"
              wheel-down: "brightnessctl s 2%-"

    # do volume and battery
    - pipewire:
        content:
          map:
            on-click:
              wheel-up: pamixer -i 2
              wheel-down: pamixer -d 2
              left: footclient -T pulsemixer pulsemixer
              right: pamixer -t

            conditions:
              muted && type == "sink":
                string: {text: "󰸈 {cubic_volume}%", foreground: *red}
              ~muted && type == "sink":
                ramp:
                  tag: cubic_volume
                  items:
                    - string: {text: " {cubic_volume}%"}
                    - string: {text: "󰖀 {cubic_volume}%"}
                    - string: {text: "󰕾 {cubic_volume}%"}

    - script:
        path: ~/.local/bin/antenna
        args:
          - "-y bluetooth"
        poll-interval: 3000
        content:
          map:
            on-click:
              left: sh -c "antenna -c bluetooth && bt -c"
              right: "antenna -t bluetooth"
            conditions:
              bluetooth: {string: {text: 󰂯}}
              ~bluetooth: {string: {text: 󰂲, foreground: *red}}

    - network:
        spacing: 0
        content:
          map:
            right-margin: *dmargin
            on-click:
              left: "notify-send 'TODO: Implement bring up network manager'"
              right: "antenna -t wifi"

            conditions:
              (name == "enp9s0u2u1u2" || name == "enp0s31f6") && state == "up":
                string: {text: 󰈀}
              name == "wlan0":
                map:
                  default:
                    string: {text: 󰤭, foreground: *red}
                  conditions:
                    ssid != "":
                      ramp:
                        tag: quality
                        items:
                          - string: {text: "󰤯 {ssid}"}
                          - string: {text: "󰤟 {ssid}"}
                          - string: {text: "󰤢 {ssid}"}
                          - string: {text: "󰤥 {ssid}"}
                          - string: {text: "󰤨 {ssid}"}
    - river:
        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              id > 7:
                string: {text: }
              urgent:
                string: {text: "{id}", margin: *margin, deco: { background: {color: *red} }}
              focused:
                string: {text: "{id}", margin: *margin, deco: { background: {color: *green} }}
              occupied:
                string: {text: "{id}", margin: *margin }

  right:
    - mpd:
        port: 6600
        host: "127.0.0.1"
        content:
          map:
            on-click:
              left: "mpc toggle"
              right: sh -c "riverctl set-focused-tags $((1 << 3)) && pgrep ncmpcpp || setsid -f footclient ncmpcpp"
            conditions:
              state == stopped:
                - string: {text: 󰝛}
                - string: {text: " Stopped", foreground: ffffff66}
              state == offline:
                - string: {text: 󰝛}
                - string: {text: " Offline", foreground: ffffff66}
              (state == paused || state == playing) && (artist != "" && title != ""):
                list:
                  spacing: 0
                  items:
                    - string: {text: "󰝚 "}
                    - map:
                        conditions:
                          state == playing: {string: {text: "{artist}"}}
                          state == paused: {string: {text: "{artist}", foreground: ffffff66}}
                    - string: {text: " | ", foreground: ffffff66}
                    - map:
                        conditions:
                          state == playing: {string: {text: "{title}", foreground: ffa0a0ff}}
                          state == paused: {string: {text: "{title}", foreground: ffffff66}}
                    - map:
                        conditions:
                          state == playing: {string: {text: " | {pos}/{end}"}}
                          state == paused: {string: {text: " | {pos}/{end}", foreground: ffffff66}}
              (state == paused || state == playing):
                list:
                  spacing: 0
                  items:
                    - string: {text: "󰝚 "}
                    - map:
                        conditions:
                          state == playing: {string: {text: "{file}"}}
                          state == paused: {string: {text: "{file}", foreground: ffffff66}}
                    - map:
                        conditions:
                          state == playing: {string: {text: " | {pos}/{end}"}}
                          state == paused: {string: {text: " | {pos}/{end}", foreground: ffffff66}}

    - clock:
        date-format: "%a %d/%m/%Y"
        content:
          - string: { text: " {date}", right-margin: *margin-side, on-click: sh -c "riverctl set-focused-tags $((1 << 5)) && setsid -f gnome-calendar" }
          - string: { text: "󱑃 {time}", left-margin: *margin-side }

    - label:
        content:
          string:
            on-click: "wlogout"
            text: 󰐥
