#!/bin/sh
term=footclient

# ----------#
# Move mode #
# ----------#

riverctl declare-mode move
riverctl map normal Super+Alt M enter-mode move
riverctl map move None Escape enter-mode normal

riverctl map move None J swap down
riverctl map move None K swap up
riverctl map move None H swap left
riverctl map move None L swap right

riverctl map move None Period send-to-output next
riverctl map -release move None Period focus-output next
riverctl map move None Comma send-to-output previous
riverctl map -release move None Comma focus-output previous
riverctl map move Alt Period send-to-output next
riverctl map move Alt Comma send-to-output previous

# -----------------#
# Normal/Move mode #
# -----------------#

# Tags
i=0
for t in C T D I M G N O # Code Tests Docs Internet Media Games Notes Other
do
    tags=$((1 << i))

    riverctl map move None "$t" set-view-tags "$tags"
    riverctl map -release move None "$t" set-focused-tags "$tags"
    riverctl map move Shift "$t" toggle-view-tags "$tags"
    riverctl map move Alt "$t" set-view-tags "$tags"

    riverctl map normal Super "$t" set-focused-tags "$tags"
    riverctl map normal Super+Shift "$t" toggle-focused-tags "$tags"

    i=$((i + 1))
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super A set-focused-tags $all_tags
riverctl map move None A set-view-tags $all_tags

# Change focused window/tag/monitor
riverctl map normal Super J focus-view down
riverctl map normal Super K focus-view up
riverctl map normal Super H focus-view left
riverctl map normal Super L focus-view right
riverctl map normal Super F toggle-fullscreen
riverctl map normal Super Z zoom

riverctl map normal Super Period focus-output right
riverctl map normal Super Comma focus-output left

# Mouse controls for floating views
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# Change layout
riverctl map normal Super+Alt H send-layout-cmd rivercarro "main-ratio +0.05"
riverctl map normal Super+Alt L send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal Super+Alt K send-layout-cmd rivercarro "main-count +1"
riverctl map normal Super+Alt J send-layout-cmd rivercarro "main-count -1"

# Open/Close programs/tags
riverctl map normal Super+Control B spawn "$BROWSER"                                             # B for browser
riverctl map normal Super+Control C spawn "qalculate-gtk"                                        # C for calculator
riverctl map normal Super+Control E spawn "foot -f monospace:pixelsize=20 -T emoji-picker emoji" # E for emoji
riverctl map normal Super+Control F spawn "nemo" 												 # F for Files
riverctl map normal Super+Control G spawn "steam" 												 # G for Games
riverctl map normal Super+Control L spawn "swaylock"                                      		 # L for lock
riverctl map normal Super+Control M spawn "music"                                      			 # M for Music
riverctl map normal Super+Control N spawn "neovide"                                              # N for neovide
riverctl map normal Super+Control Q spawn "qr"                                                   # Q for QR
riverctl map normal Super+Control R spawn "fuzzel"                                               # R for run
riverctl map normal Super+Control T spawn "$term"                                                # T for terminal
riverctl map normal Super+Control V spawn "$term -T pulsemixer pulsemixer"                       # V for volume
riverctl map normal Super+Control W spawn "wl-color-picker"                                      # W for color wheel
riverctl map normal Super+Control X close                                                        # X as in the X icon to close

#------------#
# Float mode #
#------------#

riverctl declare-mode float
riverctl map normal Super+Alt F enter-mode float
riverctl map float None Escape enter-mode normal

riverctl map float None T toggle-float

move_step=50
riverctl map -repeat float None H move left  "$move_step"
riverctl map -repeat float None J move down  "$move_step"
riverctl map -repeat float None K move up    "$move_step"
riverctl map -repeat float None L move right "$move_step"

riverctl map float Alt H snap left
riverctl map float Alt J snap down
riverctl map float Alt K snap up
riverctl map float Alt L snap right

resize_step=50
riverctl map -repeat float Control H resize horizontal -"$resize_step"
riverctl map -repeat float Control J resize vertical   -"$resize_step"
riverctl map -repeat float Control K resize vertical    "$resize_step"
riverctl map -repeat float Control L resize horizontal  "$resize_step"

#------------------#
# Passthrough mode #
#------------------#

# This mode has only a single mapping to return to normal mode.
# This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough
riverctl map normal Super+Alt F11 enter-mode passthrough
riverctl map passthrough Super+Alt F11 enter-mode normal

#----------------------#
# All modes + Switches #
#----------------------#

for mode in normal locked float move
do
    riverctl map -repeat "$mode" None XF86AudioRaiseVolume spawn 'pamixer -i 2'
    riverctl map -repeat "$mode" None XF86AudioLowerVolume spawn 'pamixer -d 2'
    riverctl map         "$mode" None XF86AudioMute        spawn 'pamixer -t'

    # "$mod4" MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map "$mode" None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map "$mode" None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map "$mode" None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map "$mode" None XF86AudioNext  spawn 'playerctl next'

    riverctl map "$mode" None Print spawn 'screenshot'

    riverctl map -repeat "$mode" None XF86MonBrightnessUp   spawn 'brightnessctl set +2%'
    riverctl map -repeat "$mode" None XF86MonBrightnessDown spawn 'brightnessctl set 2%-'

    # The antenna keys are hardware switches on my laptop so no need to bind them
done
